### ISSUE TITLE
Does this script support latest stash app version database?

### ISSUE THREAD

**Issue by IntoTheBlackHole** [ALonelyJuicebox/OFMetadataToStash#12]
```
Invoke-SqliteQuery: /home/alex/opt/OFMetadataToStash-0.4/OFMetadataToStash.ps1:264
Line |
 264 |  … eryResult = Invoke-SqliteQuery -Query $Query -DataSource $PathToStash …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Fill" with "1" argument(s): "SQL logic error no such column: scenes.path"
Invoke-SqliteQuery: /home/alex/opt/OFMetadataToStash-0.4/OFMetadataToStash.ps1:275
Line |
 275 |  … eryResult = Invoke-SqliteQuery -Query $Query -DataSource $PathToStash …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Fill" with "1" argument(s): "SQL logic error no such column: path"
```

### INFO ###
There's a file in this OnlyFans metadata database that we couldn't find in your Stash database but the file IS on your filesystem.
It could be a duplicate that Stash decided not to import, but try running a Scan Task in Stash then re-running this script.

I verified the file exists in stash. But still can't make it work.

**Comment by ALonelyJuicebox** [comment]
Sorry for the hassle, just now realizing I messed up the release a bit-- while the file in the body of the release was accurate, the "source code" zip was not. Should be fixed now!
https://github.com/ALonelyJuicebox/OFMetadataToStash/releases/tag/v0.4a

**Comment by IntoTheBlackHole** [comment]
Thanks a lot. `v0.4a` is working for me. But I had to symlink `utilities` folder to make it work.  
error:
`Error: Could not find 'utilities/stash_example_db.sqlite'. Please redownload this script from Github.`
fix:
`ln -s Utilities utilities`

Hope you will fix this in next release. Thanks again.

**Comment by ALonelyJuicebox** [comment]
Thanks for the feedback. For clarity, what operating system are you running?

**Comment by IntoTheBlackHole** [comment]
I am running Void Linux.
