### ISSUE TITLE
database schema incompatibility

### ISSUE THREAD

**Issue by miglety** [ALonelyJuicebox/OFMetadataToStash#13]
Looks like the stash db schema has been updated and now im seeing this. I assume a script update is needed?

```
OnlyFans Metadata to Stash Database PoSH Script

Your Stash database has a newer database schema than expected!
(Expected version 41, your Stash database is running Stash schema version 43)
Checking for incompatibility...

- Hmm...The 'Images' table has been modified in this new db schema
- Hmm...The 'Performers' table has been modified in this new db schema

For the reason(s) mentioned above, your database may be incompatible with this script
Running this script may change your database in unexpected, untested ways.

1 - Press [Enter] to exit.
2 - You may override this warning by entering the phrase 'Never tell me the odds!', then pressing [Enter]

What would you like to do?:
```

**Comment by ALonelyJuicebox** [comment]
Thanks for the feedback! The dev build addresses this as of today (3/7/2023)
Please expect a proper release by end of week once I finish doing my QA and adding a few additional features. 🙂

**Comment by ValurionSama** [comment]
Hello ALonelyJuiceBox ! 
First of all, thank you for your work, this scraper looks so promising.

I'm currently having a problem with the latest release, I also have an incompatibility with DB Stash, can you do anything about it?

I tested the version of the dev branch, I no longer have this incompatibility in the database schema but on the other hand no metadata is imported into Stash, do you know why? 

Thanks in advance! 
 [
![2023-07-12_02-47](https://github.com/ALonelyJuicebox/OFMetadataToStash/assets/129330705/24a91b8f-ae68-4cb7-a9b4-202f7959a542)
](url)
