### ISSUE TITLE
dev branch incompatible with Stash v0.20.2

### ISSUE THREAD

**Issue by Sk8Code8** [ALonelyJuicebox/OFMetadataToStash#16]
Looks like the latest dev branch is incompatible with Stash v0.20.2 build hash e685f80e.

![image](https://github.com/ALonelyJuicebox/OFMetadataToStash/assets/133833865/52c08861-09fd-4581-a233-380f09f5ca83)

**Comment by ekvq** [comment]
looks like the dev branch may have broken again with v0.21.0 Build hash: 9180a68c

**Comment by ALonelyJuicebox** [comment]
Latest build should address this schema issue!
