### ISSUE TITLE
Changes to database schema (48) in v0.22.x

### ISSUE THREAD

**Issue by zzfet** [ALonelyJuicebox/OFMetadataToStash#17]
Stash has modified the way that scene URLs are handled in version 0.22 (in order to allow for multiple links for a scene). Specifically:
* The 'url' column has been removed from the 'scenes' table.
* A new table, 'scene_urls', has been added. This contains three columns: 'scene_id' (corresponding to the scene ID in the 'scenes' table), 'position' (the position of the link in the URL list), and 'url'.

At present, the script flags an error during this segment due to the url column being removed from 'scene':
`                                #Updating scene metadata if necessary
                                if (($StashDB_QueryResult.scenes_title -ne $proposedtitle) -or ($StashDB_QueryResult.scenes_details -ne $OFDBMedia.text)){
                                    $Query = "UPDATE scenes SET title='"+$proposedtitle+"', details='"+$detailsToAddToStash+"', date='"+$creationdatefromOF+"', updated_at='"+$modtime+"', url='"+$linktoperformerpage+"', studio_id='"+$OnlyFansStudioID+"' WHERE id='"+$StashDB_QueryResult.scenes_id+"'"
                                    Invoke-SqliteQuery -Query $Query -DataSource $PathToStashDatabase
                                    $filewasmodified = $true
                                }`

From what I gather, it should be a case of removing the 'url' from the initial scene update query, and adding a new 'INSERT INTO' query for the scene_urls database.

**Comment by ALonelyJuicebox** [comment]
Latest build should address this! Please let me know if any bugs!
