### ISSUE TITLE
Write Metadata to Stash Database over the Network

### ISSUE THREAD

**Issue by gentlesartori** [ALonelyJuicebox/OFMetadataToStash#18]
I have my StashApp server installed in TrueNAS SCALE Kubernetes / Docker app. Any way to send the metadata to Stash without accessing the SQLLite database?

**Comment by ALonelyJuicebox** [comment]
Latest build now uses Stash's API for queries rather than direct SQL commands as it previously did. Should work for your use case-- please let me know!
