### ISSUE TITLE
Issue when media not stored in the same location the database expects.

### ISSUE THREAD

**Issue by ne0lith** [ALonelyJuicebox/OFMetadataToStash#19]
```
Info: There's a file in this OnlyFans metadata database that we couldn't find in your Stash database.
This file also doesn't appear to be on your filesystem.
Try rerunning the OnlyFans script and redownloading the file.

- __user_data__\sites\OnlyFans\username\Posts\Free\Images\2316x3088_filename.jpg
```

The issue is, the file IS in my stash db, it's just not using the same path the DB stored it. 

I.e. my media doesn't stay in the same location it was scraped to.

Expected path:
`- __user_data__\sites\OnlyFans\username\Posts\Free\Images\2316x3088_filename.jpg`

Real path potential 1:
`B:\collections\username\images\2316x3088_filename.jpg`

Real path potential 2:
`B:\collections\username\premium\2316x3088_filename.jpg`

Or it may not follow that format either, but i would think if the `2316x3088_filename.jpg` exists within the stashdb, and the filesize is the same, it ought to match?

Surely there's ways to still leverage the db file if the file size hasn't changed, and the filename is 1:1 in the stash db.

**Comment by n30liberal** [comment]
Tried normal, and it wasn't working. Moved to low, and I think it should work the exact way I asked here. So that is my bad. But getting a new issue, can open a new issue if required.

```
Which performer would you like to select [Enter a number]: 282
OK, the performer 'USERNAME' will be processed.

Quick Tips:
   * Be sure to run a Scan task in Stash of your OnlyFans content before running this script!
   * Be sure your various OnlyFans metadata database(s) are located either at
     <performername> \user_data.db or at <performername>\metadata\user_data.db

Press [Enter] to begin:


Info: Parsing media for pastelwife
(8) Error: Could not communicate to Stash using the URL in the config file (http://localhost:9999/graphql)
Press [Enter] to exit:
```

The issue is, i can clearly access the graphql from that endpoint in my browser.

**Comment by ALonelyJuicebox** [comment]
I have a feeling it has to do with some character in the details field of a given video/image that's not being escaped properly. I'll upload 0.6 later this evening and you can let me know if this addresses the issue/gives you more information for troubleshooting purposes

**Comment by ALonelyJuicebox** [comment]
Sorry for the wait-- can you run 0.6 and see if it fixes things?
https://github.com/ALonelyJuicebox/OFMetadataToStash/releases/tag/v0.6

**Comment by ne0lith** [comment]
Seems to be working now, at least for the user I had tried before.
