### ISSUE TITLE
[Feature] Path translation (for Docker)

### ISSUE THREAD

**Issue by ALonelyJuicebox** [ALonelyJuicebox/OFMetadataToStash#2]
Because the path to a given media file (in stash) fundamentally differs from from the path that might be seen in the OnlyFans database, I need to add support for auto translating chunks of a path if manually defined in the config file

I also need to copy the stash db file to a local path to avoid SQLite issues that occur when accessing the db over a network connection

**Comment by BlissfulMayer** [comment]
I've fixed this here: https://github.com/ALonelyJuicebox/OFMetadataToStash/pull/8
