### ISSUE TITLE
Feature request: Ability to skip importing image meta data.

### ISSUE THREAD

**Issue by ne0lith** [ALonelyJuicebox/OFMetadataToStash#20]
Would love an option to avoid importing db data for images.

**Comment by ALonelyJuicebox** [comment]
That's a great feature request, I'll get this done.

**Comment by ALonelyJuicebox** [comment]
Added feature in 0.6
https://github.com/ALonelyJuicebox/OFMetadataToStash/releases/tag/v0.6
