### ISSUE TITLE
Post description as title config option

### ISSUE THREAD

**Issue by toddhow** [ALonelyJuicebox/OFMetadataToStash#25]
Add a config option to use the post description instead of `post_author - YYYY-MM-DD`.

**Comment by ALonelyJuicebox** [comment]
I appreciate the effort-- I'm a little hesitant to add the PR you submitted for a couple reasons

1.) I'm not sure I follow the logic of setting a post description to an entirely different object in Stash made with a different purpose. The "Details" object seems like an accurate place for that metadata.

2.) While this script isn't inherently made for integration with a Stashbox, from a community contribution perspective, setting the title to be equal to an OF Post description (which regularly can be multi-line) also seems to be against the[ current rules](https://docs.fansdb.cc/scenes.html) of Stashboxes like FansDB. 

Ideally I'd like to try and push users to be as good of a metadata steward as possible, even at the cost of fewer options.

**Comment by ALonelyJuicebox** [comment]
TBH the script will likely change fairly little after 0.8 (I just fixed some statistics things in the upcoming build) so if you want to keep on using the fork you made here at 0.7 or fork it at the upcoming 0.8 release, you'd have exactly what you want. 🙂
