### ISSUE TITLE
Adding to Unraid

### ISSUE THREAD

**Issue by dildosven** [ALonelyJuicebox/OFMetadataToStash#29]
Is there some way to add this to unraid? If not, this is a feature request

**Comment by ALonelyJuicebox** [comment]
Hey! Can you elaborate a bit more? My content is on my NAS (TrueNAS, specifically) and I run this script without issue.

**Comment by twist3dimages** [comment]
> Is there some way to add this to unraid? If not, this is a feature request

You can run it if you install NerdTools and making sure this is turrned on 

![image](https://github.com/ALonelyJuicebox/OFMetadataToStash/assets/33134502/b0e2f4c1-b07f-4080-b916-f0195af95f81)

If you're talking about a Docker container, I could try and make one
