### ISSUE TITLE
[BUG] Single quotes in description are saved as double single quote

### ISSUE THREAD

**Issue by Sadarex** [ALonelyJuicebox/OFMetadataToStash#35]
Hi, there is an issue with single quotes in OF post texts.

If there is for example:
`I'm`

inside the text, it results in:
`I''m`

as the description inside Stash.

**Comment by ALonelyJuicebox** [comment]
This has to do with the input sanitization in the script-- I can replicate this issue, I'll see if I can address it for 0.9.

**Comment by ALonelyJuicebox** [comment]
Resolved with 0.9 release
