### ISSUE TITLE
[BUG] (sometimes) Selecting wrong studio, if similar studio already exists

### ISSUE THREAD

**Issue by Sadarex** [ALonelyJuicebox/OFMetadataToStash#36]
The tool can have a mismatch for the selected studio, if there are multiple "OnlyFans" studios.

Example:

I had scenes which were linked with the studio "amandawelp (OnlyFans)".
When I rescraped the content some (not all) scenes got linked to the already existing studio "adorable_alice (OnlyFans)".

**Comment by ALonelyJuicebox** [comment]
Thanks for the report-- I'll make the query more specific to mitigate this issue for now. In the future I'll consider performer names to be created as child studios similar to how fansdb handles things.

**Comment by Sadarex** [comment]
Fixed in v0.9 release
