### ISSUE TITLE
[Help] OF metadata not being added to videos in Stash

### ISSUE THREAD

**Issue by purebot8** [ALonelyJuicebox/OFMetadataToStash#5]
Upon running the Powershell script, the only metadata that seems to be added to Stash are:
- A performer gets created with an OF url,
- The performer is added to the videos & images.

It doesn't appear to add any other metadata, like the post details, post url, creation date etc.

The only thing I can think of that might contribute to that, is that I have changed the default filename in the DC script to include the performer username, as below:

```"filename_format": "{model_username}-{media_id}-{filename}.{ext}",```

I'm running DC OF v7.6.1 and OFMetadataToStash v0.3.

Just wondering if there is any other configuration I might be missing?

**Comment by ALonelyJuicebox** [comment]
Just making sure, when you run the script, are you entering "1" when initially prompted for "How would you like to process your content?".

**Comment by purebot8** [comment]
Correct and it points directly at the performer's root folder. Currently, only running this on one performer at a time

**Comment by ALonelyJuicebox** [comment]
give the new release a go! 🙂
